name: ActionBlocker
version: 1.0
api-version: 1.20
main: io.github.bigcookie233.blocker.ActionBlocker
author: BigCookie233
permissions:
  actionblocker.bypass:
    description: 绕过所有动作限制
    default: op
